/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Courvois (https://sketchfab.com/CourvoisZ)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-stack-of-money-632cf7dbc59a496283d1a6092dc6f9b0
title: Low Poly Stack of Money
*/

import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/low_poly_stack_of_money-transformed.glb'
  ) as GLTFResult
  const moneyRef = useRef<THREE.Group>(null!)

  // useFrame(() => {
  //   if (!moneyRef.current) return
  //   moneyRef.current.rotation.y += 0.009
  //   moneyRef.current.rotation.x += 0.005
  //   // moneyRef.current.rotation.z += 0.01
  // })
  return (
    <group
      {...props}
      dispose={null}
      ref={moneyRef}
      position={[0, 0, 0]}
      rotation={[0.6, -8, -0.5]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.7, 0]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.Material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_stack_of_money-transformed.glb')
